baseURL = "https://aidanmaurinjones.com/"
languageCode = "en-us"
title = "Aidan Maurin-Jones"
theme = "hermit-v2"

relativeURLs = true
enableRobotsTXT = true

[params]
  author = "Aidan Maurin-Jones"
  description = "Links to all my adventures on the web"
  homeSubtitle = "Veterinary Assistant • macOS Automation Enthusiast"
  defaultTheme = "auto"  # auto-switches light/dark
  showReadingTime = false
  showDate = false