baseURL = "https://aidanmaurinjones.com"
languageCode = "en-us"
title = "Aidan Maurin-Jones"
theme = "hermit-v2"

[params]
  footerHideThemeName = true
  noIndex = true

[menu]

  [[menu.main]]
    name = "Blog"
    url = "https://blog.aidanmaurinjones.com"
    weight = 10

  [[menu.main]]
    name = "Mastodon"
    url = "https://mastodon.social/@aidanmaurinjones"
    weight = 20

  [[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/aidanmaurinjones"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "/Contact"
    weight = 40
